### ISSUE TITLE
Lmove function

### ISSUE THREAD

**Issue by eclipsedcpp** [beryldb/beryldb#1]
Hey,

Hope everything is fine. I would like to know whether it would be possible to implement an lmove module.

Thank you very much.

**Comment by cfferry** [comment]
Hey,

Yes. This is something in the radar. I'll make sure to have a working component within a couple weeks.

Thank you very much for this input.

**Comment by cfferry** [comment]
LMove has been added.

Please refer to the coremods/core_list component to a better insight: [cmd_lpush.cpp](https://github.com/beryldb/beryldb/blob/unstable/src/coremodules/core_list/cmd_lpush.cpp#L46)
