### ISSUE TITLE
Could you please provide an ssl_openssl module example

### ISSUE THREAD

**Issue by johnatannvmd** [beryldb/beryldb#12]
How to configure the server and the client?

https://github.com/beryldb/beryldb/blob/unstable/docs/conf/modules.conf.example#L100

**Comment by cfferry** [comment]
Hello Jonathan!

The SSL module may be found here https://github.com/beryldb/beryldb/blob/unstable/src/modules/extra/m_openssl.cpp 

At this time, the module is not supported on the client side. I am working on this and will report back as soon as an update comes by.

I appreciate your time!
