### ISSUE TITLE
Best way to find keys in lists?

### ISSUE THREAD

**Issue by benjasohns** [beryldb/beryldb#4]
Hello,

Hope this issue finds you all well. I'm trying to find a good way to find elements in a given list. Is there any predefined command for this?

Great work, look forward to see newer releases! 👍

**Comment by cfferry** [comment]
Hey Benjasohns,

Yes. We are working in two relevant functions at this time: lfind and lsearch. Feel free to check back for updates next week.  We're always accepting new ideas as well, so feel free to write them down ✌️

Have a great weekend.

**Comment by cfferry** [comment]
Hello,

Commands LFIND and LSEARCH are now fully functional.

If you wish to check proper usage, feel free to run these commands using CLI:

beryl> **syntax** lfind
beryl> <key> <%value> <limit> <offset>
beryl> **syntax** lsearch
beryl> <%key> <limit> <offset>

Keep in mind that a **%** before each tag means that wildcards are allowed (`ie`: *hello*)

Enjoy your weekend!
