### ISSUE TITLE
Command to get core modules

### ISSUE THREAD

**Issue by benjasohns** [beryldb/beryldb#5]
Hello team:

Wouldn't it be great to have a command to list core modules? 
I understand that $MODULES will list all available modules, however, a better approach may be to have two commands for this, or having one command that takes arguments.

I suggest having one MODULES command capable of handling arguments:

$MODULES core

and:

$MODULES opt

Would this be a good thing to have?

Thanks, and keep the work!

**Comment by cfferry** [comment]
I have added command **Coremodules**. 

This feature will be available in the upcoming release.

Enjoy your day.
