### ISSUE TITLE
What’s your level of compatibility with Redis?

### ISSUE THREAD

**Issue by adulau** [beryldb/beryldb#6]
Some commands of BerylDB seems to be close to Redis but some Redis commands are missing such as ‘hgetall’.  Do you plan to be fully compatible or just having a subset ? Thank you

**Comment by cfferry** [comment]
Hello Alexandre,

Thanks for your inquiry, we're certainly glad to hear from you.

Beryl is an independent project and is not meant to have all functionalities of other databases. However, we are trying to implement as many functionalities as possible and this will be visible in upcoming releases.

Our [core component](https://github.com/beryldb/beryldb/tree/unstable/src/coremods) is now fully functional (it has been lots of work!) and adding new commands is becoming a relatively straightforward process. At this point, we are trying to fix the internals of the system "as a whole" before releasing a fully functional database (1.0). That being said, hgetall will certainly be part of the core at some point.

I really appreciate your question, keep tuned! 👍
